name: trial-test
favicon: null
layout_spectrum: 0.9867342363577336
typography_spectrum: 0.7920837979763746
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5412940096575767
  lightness: 0.6817238985095173
  saturation: 0.5049625944811851
  rhythmicContrast: 0.6002360943239182
purpose: []
